# This is an example ant build template
# This pipeline clones the source repostiory & build ant application, then saves the jar artifacts

version: 1.0

stages:
  stage1:
    jobs:
    - [clonejob]
  stage2:
    jobs:
    - [buildjob]

jobs:
  clonejob:
    description: repository cloning job
    type: source-checkout
    parameters:
      service: gitlab
      integration: gitlab_NationalSystem
      repo: cm-ant-standalone-test
      branch: master
  buildjob:
    description: build project using ant
    type: ant
    parameters:
      requiredArtifacts:
      - clonejob
      image: ant:latest
      artifacts:
      - '**/build/**/*.jar'
      captureunittests: 'true'
      testresultfiles: '**/TEST-*.xml'
